// Code generated by "stringer -type=Modifier"; DO NOT EDIT.

package item

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BaseMinDamageModifier-0]
	_ = x[BaseMaxDamageModifier-1]
	_ = x[BaseDamageModifier-2]
	_ = x[DamageMultiplierModifier-3]
	_ = x[PreparationModifier-4]
	_ = x[ActionPointModifier-5]
}

const _Modifier_name = "BaseMinDamageModifierBaseMaxDamageModifierBaseDamageModifierDamageMultiplierModifierPreparationModifierActionPointModifier"

var _Modifier_index = [...]uint8{0, 21, 42, 60, 84, 103, 122}

func (i Modifier) String() string {
	if i < 0 || i >= Modifier(len(_Modifier_index)-1) {
		return "Modifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Modifier_name[_Modifier_index[i]:_Modifier_index[i+1]]
}
