// Code generated by "stringer -output=./character_string.go -type=CharacterSex,CharacterPerformance"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Male-0]
	_ = x[Female-1]
}

const _CharacterSex_name = "MaleFemale"

var _CharacterSex_index = [...]uint8{0, 4, 10}

func (i CharacterSex) String() string {
	if i < 0 || i >= CharacterSex(len(_CharacterSex_index)-1) {
		return "CharacterSex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CharacterSex_name[_CharacterSex_index[i]:_CharacterSex_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PerformIdle-0]
	_ = x[PerformMove-1]
	_ = x[PerformSkill1-2]
	_ = x[PerformSkill2-3]
	_ = x[PerformSkill3-4]
	_ = x[PerformHurt-5]
	_ = x[PerformDying-6]
	_ = x[PerformVictory-7]
}

const _CharacterPerformance_name = "PerformIdlePerformMovePerformSkill1PerformSkill2PerformSkill3PerformHurtPerformDyingPerformVictory"

var _CharacterPerformance_index = [...]uint8{0, 11, 22, 35, 48, 61, 72, 84, 98}

func (i CharacterPerformance) String() string {
	if i < 0 || i >= CharacterPerformance(len(_CharacterPerformance_index)-1) {
		return "CharacterPerformance(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CharacterPerformance_name[_CharacterPerformance_index[i]:_CharacterPerformance_index[i+1]]
}
