// Code generated by "stringer -type=Mastery"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShortRangeMeleeMastery-0]
	_ = x[LongRangeMeleeMastery-1]
	_ = x[RangedCombatMastery-2]
	_ = x[CraftsmanshipMastery-3]
	_ = x[FireMastery-4]
	_ = x[WaterMastery-5]
	_ = x[EarthMastery-6]
	_ = x[AirMastery-7]
	_ = x[LightningMastery-8]
	_ = x[DarkMastery-9]
	_ = x[LightMastery-10]
}

const _Mastery_name = "ShortRangeMeleeMasteryLongRangeMeleeMasteryRangedCombatMasteryCraftsmanshipMasteryFireMasteryWaterMasteryEarthMasteryAirMasteryLightningMasteryDarkMasteryLightMastery"

var _Mastery_index = [...]uint8{0, 22, 43, 62, 82, 93, 105, 117, 127, 143, 154, 166}

func (i Mastery) String() string {
	if i < 0 || i >= Mastery(len(_Mastery_index)-1) {
		return "Mastery(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mastery_name[_Mastery_index[i]:_Mastery_index[i+1]]
}
