// Code generated by "stringer -type=ObstacleType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NonObstacle-0]
	_ = x[CharacterObstacle-1]
	_ = x[CrevasseObstacle-2]
	_ = x[TreeObstacle-3]
	_ = x[DeepWaterObstacle-4]
	_ = x[MudObstacle-5]
}

const _ObstacleType_name = "NonObstacleCharacterObstacleCrevasseObstacleTreeObstacleDeepWaterObstacleMudObstacle"

var _ObstacleType_index = [...]uint8{0, 11, 28, 44, 56, 73, 84}

func (i ObstacleType) String() string {
	if i < 0 || i >= ObstacleType(len(_ObstacleType_index)-1) {
		return "ObstacleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObstacleType_name[_ObstacleType_index[i]:_ObstacleType_index[i+1]]
}
