// Code generated by "stringer -type=ObstacleType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CharacterObstacle-0]
	_ = x[CrevasseObstacle-1]
	_ = x[TreeObstacle-2]
}

const _ObstacleType_name = "CharacterObstacleCrevasseObstacleTreeObstacle"

var _ObstacleType_index = [...]uint8{0, 17, 33, 45}

func (i ObstacleType) String() string {
	if i < 0 || i >= ObstacleType(len(_ObstacleType_index)-1) {
		return "ObstacleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObstacleType_name[_ObstacleType_index[i]:_ObstacleType_index[i+1]]
}
