// Code generated by "stringer -type=StatType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HPStat-0]
	_ = x[EnergyStat-1]
	_ = x[ActionStat-2]
	_ = x[PrepStat-3]
}

const _StatType_name = "HPStatEnergyStatActionStatPrepStat"

var _StatType_index = [...]uint8{0, 6, 16, 26, 34}

func (i StatType) String() string {
	if i < 0 || i >= StatType(len(_StatType_index)-1) {
		return "StatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatType_name[_StatType_index[i]:_StatType_index[i+1]]
}
