// Code generated by "stringer -type=TeamControl"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocalControl-0]
	_ = x[ComputerControl-1]
}

const _TeamControl_name = "LocalControlComputerControl"

var _TeamControl_index = [...]uint8{0, 12, 27}

func (i TeamControl) String() string {
	if i < 0 || i >= TeamControl(len(_TeamControl_index)-1) {
		return "TeamControl(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TeamControl_name[_TeamControl_index[i]:_TeamControl_index[i+1]]
}
