version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/hajimehoshi/ebiten/v2
    versions:
    - 2.0.3
    - 2.0.4
    - 2.0.5
    - 2.0.6
    - 2.0.7
