// Code generated by "stringer -type=CombatState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AwaitingInputState-0]
	_ = x[ExecutingState-1]
	_ = x[ThinkingState-2]
	_ = x[PreparingState-3]
}

const _CombatState_name = "AwaitingInputStateExecutingStateThinkingStatePreparingState"

var _CombatState_index = [...]uint8{0, 18, 32, 45, 59}

func (i CombatState) String() string {
	if i < 0 || i >= CombatState(len(_CombatState_index)-1) {
		return "CombatState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CombatState_name[_CombatState_index[i]:_CombatState_index[i+1]]
}
