// This file was autogenerated; DO NOT EDIT
package res

import (
	"bytes"
	"fmt"
	"image"
	"image/png"
)

// Images stores decoded Images keyed by their filename as inline compiled resources.
var Images map[string]image.Image

func init() {
	Images = map[string]image.Image{}

	for _, file := range []struct {
		name string
		b    []byte
	}{} {
		decoded, err := png.Decode(bytes.NewReader(file.b))
		if err != nil {
			panic(fmt.Sprintf("png.Decode %s: %v", file.name, err))
		}
		Images[file.name] = decoded
	}
}
