// Code generated by "stringer -type=DirectionType"; DO NOT EDIT.

package geom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[N-0]
	_ = x[NE-1]
	_ = x[SE-2]
	_ = x[S-3]
	_ = x[SW-4]
	_ = x[NW-5]
}

const _DirectionType_name = "NNESESSWNWCENTER"

var _DirectionType_index = [...]uint8{0, 1, 3, 5, 6, 8, 10, 16}

func (i DirectionType) String() string {
	if i < 0 || i >= DirectionType(len(_DirectionType_index)-1) {
		return "DirectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DirectionType_name[_DirectionType_index[i]:_DirectionType_index[i+1]]
}
