// Code generated by "stringer -type=EngagementStatus"; DO NOT EDIT.

package combat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Alive-0]
	_ = x[KnockedDown-1]
	_ = x[Escaped-2]
}

const _EngagementStatus_name = "AliveKnockedDownEscaped"

var _EngagementStatus_index = [...]uint8{0, 5, 16, 23}

func (i EngagementStatus) String() string {
	if i < 0 || i >= EngagementStatus(len(_EngagementStatus_index)-1) {
		return "EngagementStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngagementStatus_name[_EngagementStatus_index[i]:_EngagementStatus_index[i+1]]
}
