// Code generated by "stringer -type=State"; DO NOT EDIT.

package combat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Uninitialised-0]
	_ = x[AwaitingInputState-1]
	_ = x[SelectingPathState-2]
	_ = x[SelectingTargetState-3]
	_ = x[ConfirmingSelectedTargetState-4]
	_ = x[ExecutingState-5]
	_ = x[ThinkingState-6]
	_ = x[PreparingState-7]
	_ = x[Celebration-8]
	_ = x[FadingIn-9]
	_ = x[FadingOut-10]
}

const _State_name = "UninitialisedAwaitingInputStateSelectingPathStateSelectingTargetStateConfirmingSelectedTargetStateExecutingStateThinkingStatePreparingStateCelebrationFadingInFadingOut"

var _State_index = [...]uint8{0, 13, 31, 49, 69, 98, 112, 125, 139, 150, 158, 167}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
