// Code generated by "stringer -type=State"; DO NOT EDIT.

package combat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Uninitialised-0]
	_ = x[AwaitingInputState-1]
	_ = x[SelectingTargetState-2]
	_ = x[ConfirmingSelectedTargetState-3]
	_ = x[ExecutingState-4]
	_ = x[ThinkingState-5]
	_ = x[PreparingState-6]
	_ = x[Celebration-7]
	_ = x[FadingIn-8]
	_ = x[FadingOut-9]
}

const _State_name = "UninitialisedAwaitingInputStateSelectingTargetStateConfirmingSelectedTargetStateExecutingStateThinkingStatePreparingStateCelebrationFadingInFadingOut"

var _State_index = [...]uint8{0, 13, 31, 51, 80, 94, 107, 121, 132, 140, 149}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
