// Code generated by "stringer -type=BrushType"; DO NOT EDIT.

package targeting

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SingleHex-0]
	_ = x[WithinRangeOfTarget-1]
	_ = x[WithinRangeOfOrigin-2]
	_ = x[LinearFromOrigin-3]
}

const _BrushType_name = "SingleHexWithinRangeOfTargetWithinRangeOfOriginLinearFromOrigin"

var _BrushType_index = [...]uint8{0, 9, 28, 47, 63}

func (i BrushType) String() string {
	if i < 0 || i >= BrushType(len(_BrushType_index)-1) {
		return "BrushType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BrushType_name[_BrushType_index[i]:_BrushType_index[i+1]]
}
