// Code generated by "stringer -type=SelectableType"; DO NOT EDIT.

package targeting

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SelectAnywhere-0]
	_ = x[SelectWithin-1]
	_ = x[Untargeted-2]
}

const _SelectableType_name = "SelectAnywhereSelectWithinUntargeted"

var _SelectableType_index = [...]uint8{0, 14, 26, 36}

func (i SelectableType) String() string {
	if i < 0 || i >= SelectableType(len(_SelectableType_index)-1) {
		return "SelectableType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SelectableType_name[_SelectableType_index[i]:_SelectableType_index[i+1]]
}
