// Code generated by "stringer -type=Classification"; DO NOT EDIT.

package skill

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Skill-0]
	_ = x[Attack-1]
	_ = x[Spell-2]
	_ = x[Attunement-3]
}

const _Classification_name = "SkillAttackSpellAttunement"

var _Classification_index = [...]uint8{0, 5, 11, 16, 26}

func (i Classification) String() string {
	if i < 0 || i >= Classification(len(_Classification_index)-1) {
		return "Classification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Classification_name[_Classification_index[i]:_Classification_index[i+1]]
}
