// Code generated by "stringer -type=CostType"; DO NOT EDIT.

package skill

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CostsActionPoints-0]
	_ = x[CostsMana-1]
	_ = x[CostsExhaustionPercent-2]
	_ = x[CostsHealthSacrificePercent-3]
}

const _CostType_name = "CostsActionPointsCostsManaCostsExhaustionPercentCostsHealthSacrificePercent"

var _CostType_index = [...]uint8{0, 17, 26, 48, 75}

func (i CostType) String() string {
	if i < 0 || i >= CostType(len(_CostType_index)-1) {
		return "CostType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CostType_name[_CostType_index[i]:_CostType_index[i+1]]
}
