// Code generated by "stringer -type=InjuryType"; DO NOT EDIT.

package skill

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BleedingInjury-0]
}

const _InjuryType_name = "BleedingInjury"

var _InjuryType_index = [...]uint8{0, 14}

func (i InjuryType) String() string {
	if i < 0 || i >= InjuryType(len(_InjuryType_index)-1) {
		return "InjuryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InjuryType_name[_InjuryType_index[i]:_InjuryType_index[i+1]]
}
