// Code generated by "stringer -type=TimingPoint"; DO NOT EDIT.

package skill

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttackApexTimingPoint-0]
	_ = x[EndTimingPoint-1]
}

const _TimingPoint_name = "AttackApexTimingPointEndTimingPoint"

var _TimingPoint_index = [...]uint8{0, 21, 35}

func (i TimingPoint) String() string {
	if i < 0 || i >= TimingPoint(len(_TimingPoint_index)-1) {
		return "TimingPoint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimingPoint_name[_TimingPoint_index[i]:_TimingPoint_index[i+1]]
}
