// Code generated by "stringer -type=ElementType"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UIElement-0]
	_ = x[PanelElement-1]
	_ = x[PaddingElement-2]
	_ = x[RowElement-3]
	_ = x[ColumnElement-4]
	_ = x[TextElement-5]
	_ = x[ButtonElement-6]
	_ = x[ImageElement-7]
}

const _ElementType_name = "UIElementPanelElementPaddingElementRowElementColumnElementTextElementButtonElementImageElement"

var _ElementType_index = [...]uint8{0, 9, 21, 35, 45, 58, 69, 82, 94}

func (i ElementType) String() string {
	if i < 0 || i >= ElementType(len(_ElementType_index)-1) {
		return "ElementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElementType_name[_ElementType_index[i]:_ElementType_index[i+1]]
}
